### ISSUE TITLE
textract does not install with python3.10 under linux64

### ISSUE THREAD

**Issue by kochelmonster** [conda-forge/textract-feedstock#15] opened 2021-12-12 23:29 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Enter the following command: `conda create -n test-textract python=3.10 textract`
This is the output:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
textract -> argcomplete -> python[version='2.7.*|>=3.4|2.7.*|>=3.6|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.10,<3.11.0a0|>=3.4|>=3|<3']
textract -> python[version='2.7.*|>=3.6']
python=3.10The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.10.0          h543edf9_3_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                59.4.0          py310hff52083_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test-textract
    active env location : /home/michael/miniconda3/envs/test-textract
            shell level : 2
       user config file : /home/michael/.condarc
 populated config files : /home/michael/.condarc
                          /home/michael/src/larch/scripts/condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/michael/miniconda3  (writable)
      conda av data dir : /home/michael/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : file:///home/michael/src/larch/.conda-channel/linux-64
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/michael/miniconda3/pkgs
                          /home/michael/.conda/pkgs
       envs directories : /home/michael/miniconda3/envs
                          /home/michael/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.10.0 Linux/5.4.0-91-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

**Comment by jan-janssen** [comment] 2021-12-13 00:32
Basically we are waiting for https://github.com/conda-forge/speechrecognition-feedstock/pull/20

**Comment by jan-janssen** [comment] 2021-12-13 13:22
@kochelmonster The issue is fixed now I tested it with [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jan-janssen/textract/HEAD). Can you confirm it is working for you as well?

**Comment by kochelmonster** [comment] 2021-12-13 15:39
It works.
thank you.

**Closed as completed** 2021-12-13 15:52 UTC
